### ISSUE TITLE
[Bug]: Check return type argument causing broken response on `create_notification`

### ISSUE THREAD

**Issue by luqmansen** [OneSignal/onesignal-python-api#21]
### What happened?

When calling `create_notification` with all kwargs defaulted, it will result in `{}` response because the serializer model failed to serialize the response. 

The default value for `_check_return_type` is True, which will check for returned type from the server.

This is the expected class of the response
```python
class CreateNotificationSuccessResponse:
  id: str
  recipients: int
  external_id: (str, none_type)
  errors: Notification200Errors
```
This is the `Notification200Errors` class 
```python
class Notification200Errors:
 oneOf: [InvalidIdentifierError, NoSubscribersError]

```
This is the possible composed class for Notification200Errors
```python
class InvalidIdentifierError:
 invalid_external_user_ids: [str]
 invalid_player_ids': [str]

class NoSubscribersError:
  value: [str]
```

This is what returned from the server
```json
{
"id": "",
"errors": ["All included players are not subscribed"]
}
```
The `errors` key didn't follow the defined schema, thus it broke the code.
```
onesignal.exceptions.ApiTypeError: Invalid type for variable 'value'. Required value type is list and passed type was str at ['received_data']['errors']['value']
```

### Steps to reproduce?

1. Using onesignal-python-api 2.0.0
2. Create the notification using sdk, specify destination to an unsubscribed user, or a non-existent user

```python 
    with onesignal.ApiClient(configuration) as api_client:
        api_instance = default_api.DefaultApi(api_client)
        try:
            response = api_instance.create_notification(
                Notification(
                    include_external_user_ids=['destination'],  
                    channel_for_external_user_ids='push',
                    headings=dict(en="subject"),
                    contents=dict(en="body"),
                ),
                _check_return_type=True, # this is the default value
            )
```
3. The response will be `{}`

### What did you expect to happen?

The response should not be `{}` when the server returned `user unsubscribed` error.

This is (probably) what the deserializer expected from the server response
```json
{
"id": "",
"errors": {
  "value" : ["All included players are not subscribed"],
}
```

Checking at the code, seems like this exception is intentionally silenced.
https://github.com/OneSignal/onesignal-python-api/blob/f89f7007756b45f5676664ba53a448d6e71b7b5f/onesignal/model_utils.py#L1872-L1889.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sherwinski** [comment]
Hi, we have had no further reports of this. Please upgrade the OneSignal SDK if you or anyone is still having this issue. If this is still an issue, please open a new report with updated information and we will investigate. Thanks
