### ISSUE TITLE
[question]: How to get the APP_KEY / basic_auth_key via REST API for an APP

### ISSUE THREAD

**Issue by JacoBezuidenhout** [OneSignal/onesignal-python-api#34]
### How can we help?

Hello everyone,

I hope I am not asking a foolish question... 

I am trying to automate the creation of apps via the rest API, but I cannot set the basic_auth_key as it is read_only but also the basic auth key via the API returns None... 

How can I get the App's Rest API key via the API and my USER_KEY?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jfishman1** [comment]
For security reasons, the basic_auth_key value in the response will be returned as null by default. If you need access to this, contact OneSignal Support with the email associated with the User Auth Key used in the requests. We can assist in enabling it on a user-basis.
