### ISSUE TITLE
Documentation: missing import

### ISSUE THREAD

**Issue by juandiago** [OneSignal/onesignal-python-api#5]
Hello! From this example is not clear where to import `default_api` from, once we dive into the code we can see how to get it, but it would be nice to have it here since this is front and center on the readme file

https://github.com/OneSignal/onesignal-python-api/blob/08163d9c7e005f0abd0103c9df5144ef2889dce5/README.md?plain=1#L73

**Comment by kesheshyan** [comment]
Hey @juandiago . Thanks for reporting! We will update the doc accordingly!

**Comment by kesheshyan** [comment]
Added import to the example. Will be updated with the next version release.
